# Generated by Django 2.2 on 2019-04-18 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('STEP_FATHER', 'Step-Father'), ('STEP_MOTHER', 'Step-Mother'), ('CHILD', 'Child')], max_length=20)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'quality',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('salutation', models.CharField(blank=True, choices=[('RABBI', 'Rabbi'), ('MISS', 'Miss'), ('MS', 'Ms.'), ('MRS', 'Mrs.'), ('MR', 'Mr.'), ('DR', 'Dr.')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='SeekingQuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.Quality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
            options={
                'db_table': 'seeking_quality',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('major', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
            options={
                'db_table': 'school',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('FRIEND', 'Friend'), ('RELATIVE', 'Relative'), ('MENTOR', 'Mentor'), ('RAV', 'Rav'), ('ENGAGED', 'Engaged'), ('MARRIED', 'Married')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='social_network.User')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='social_network.User')),
            ],
            options={
                'db_table': 'relationship',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('RELATIVE', 'Relative'), ('MENTOR', 'Mentor'), ('RAV', 'Rav'), ('TEACHER', 'Teacher')], max_length=20)),
                ('phone1', models.CharField(blank=True, max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
            options={
                'db_table': 'reference',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('by_name', models.CharField(blank=True, max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='social_network.User')),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by', to='social_network.User')),
            ],
            options={
                'db_table': 'recommendation',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='PersonalQuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.Quality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
            options={
                'db_table': 'personal_quality',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(blank=True, max_length=20)),
                ('birthdate', models.DateField()),
                ('marital_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('BUSY', 'Busy'), ('ENGAGED', 'Engaged'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], default='SINGLE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
            options={
                'db_table': 'personal_info',
            },
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endorser_name', models.CharField(blank=True, max_length=100)),
                ('visible', models.BooleanField(default=True)),
                ('endorser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.PersonalQuality')),
            ],
            options={
                'db_table': 'endorsement',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addr1', models.CharField(blank=True, max_length=100)),
                ('addr2', models.CharField(blank=True, max_length=100)),
                ('addr3', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
