# Generated by Django 2.2 on 2019-04-18 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('birthdate', models.DateField()),
                ('relationship', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=100, null=True)),
                ('school', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('salutation', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('status', models.CharField(default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SeekingQuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.Quality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('major', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='Friend', max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='social_network.User')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='social_network.User')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('by_name', models.CharField(max_length=100, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='social_network.User')),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by', to='social_network.User')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalQuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.Quality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=20, null=True)),
                ('birthdate', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
        ),
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endorser_name', models.CharField(max_length=100, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('endorser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.PersonalQuality')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addr1', models.CharField(max_length=100, null=True)),
                ('addr2', models.CharField(max_length=100, null=True)),
                ('addr3', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
        ),
    ]
