# Generated by Django 2.2 on 2019-04-18 20:02

from django.db import migrations, models
import django.db.models.deletion
import social_network.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='marital_status',
            field=models.CharField(default='Single', max_length=20),
        ),
        migrations.AddField(
            model_name='phone',
            name='number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='family',
            name='relationship',
            field=models.CharField(choices=[(social_network.models.FamilyType('Father'), 'Father'), (social_network.models.FamilyType('Mother'), 'Mother'), (social_network.models.FamilyType('Brother'), 'Brother'), (social_network.models.FamilyType('Sister'), 'Sister'), (social_network.models.FamilyType('Step-Father'), 'Step-Father'), (social_network.models.FamilyType('Step-Mother'), 'Step-Mother'), (social_network.models.FamilyType('Child'), 'Child')], max_length=20),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.CharField(choices=[(social_network.models.RelationshipType('Friend'), 'Friend'), (social_network.models.RelationshipType('Relative'), 'Relative'), (social_network.models.RelationshipType('Mentor'), 'Mentor'), (social_network.models.RelationshipType('Rav'), 'Rav')], max_length=20),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[(social_network.models.ReferenceType('Relative'), 'Relative'), (social_network.models.ReferenceType('Mentor'), 'Mentor'), (social_network.models.ReferenceType('Rav'), 'Rav'), (social_network.models.ReferenceType('Teacher'), 'Teacher')], max_length=20)),
                ('phone1', models.CharField(max_length=20, null=True)),
                ('phone2', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_network.User')),
            ],
        ),
    ]
