# Generated by Django 2.2 on 2019-04-18 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_personalinfo_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='endorsement',
            name='endorser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network.User'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by', to='social_network.User'),
        ),
    ]
